volumes:
  catalog-mssql-data:

services:
  catalog-service:
    container_name: catalog-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql-db
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__CatalogDb: "Server=catalog-db-mssql;Database=CatalogDb;User Id=sa;Password=supersecretpassword;"
      
  mssql-db:
    container_name: catalog-db-mssql
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1433:1433
    volumes:
      - catalog-mssql-data:/var/opt/mssql/data
      - ./MigrateData/database_script.sql:/scripts/database_script.sql
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: supersecretpassword
    command: /bin/bash -c "sleep 5s && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P supersecretpassword -i /scripts/database_script.sql"
