volumes:
  catalog-mssql-data:
  redis-data:

services:
  catalog-service:
    container_name: catalog-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-cache
      - mssql-db
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__CatalogDb: "Server=mssql-db,1433;Database=CatalogDb;User Id=sa;Password=Super.secretpa55word;TrustServerCertificate=True;"
      ConnectionStrings__RedisConnection: "redis-cache:6379"
      
  # TODO: Add working database in compose with initialization script
  # Currently need to run the script manually after the database is up
  # NOTE: this is only needed the first time the database is created. After that, the database will persist.

  mssql-db:
    container_name: catalog-db-mssql
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1433:1433
    volumes:
      - catalog-mssql-data:/var/opt/mssql/data
      - ./MigrateData/database_script.sql:/scripts/database_script.sql
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: Super.secretpa55word
    # command: /bin/bash -c "sleep 15s && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Super.secretpa55word -C -i /scripts/database_script.sql"
  
  redis-cache:
    container_name: catalog-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
